### ISSUE TITLE
Rimozione tè e infusi dal db

### ISSUE THREAD

**Issue by dkokollari** [dkokollari/Erboristeria-Alchimia#38]
Rimuovere un tè o un infuso e aggiornare la base di dati

**Comment by dkokollari** [comment]
@marcelwandji sbaglio o questa issue è già risolta? Su `DBAccess.php` è disponibile deleteTeInfusi()

**Comment by marcelwandji** [comment]
Non ancora ho aggiunto quella funzione perché la userò per fare la rimozione del tè o infuso
